dubbo:
  provider:
    timeout: 30000
    retries: 0
    serialization: hessian2
    prefer-serialization: hessian2
  consumer:
    lazy: false
    timeout: 30000
    check: false
    retries: 0
  application:
    name: dubbo-${spring.application.name}
    qos-enable: false
    qos-accept-foreign-ip: false
    register-mode: instance
    enable-file-cache: false
  protocol:
    name: tri
    port: -1
    threadpool: virtual
    payload: 104857600
    triple:
      http3:
        enabled: false
        negotiation: false # 是否启用HTTP3协商如果设置为false，HTTP2的alt-svc协商将被跳过，从而启用HTTP3但使消费者端禁用HTTP2
      verbose: false # 是否启用冗长模式。当为真时，应用程序会生成详细的日志输出，以帮助调试和监控
  registry:
    address: consul://${app.cloud.host}:${app.cloud.port}
  scan:
    base-packages: ${app.dubbo.scan-packages}
spring:
  cloud:
    consul:
      host: ${app.cloud.host}
      port: ${app.cloud.port}
      discovery:
        service-name: ${spring.application.name}
        health-check-interval: 15s
        health-check-timeout: 5s
        health-check-path: /healthz
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${random.uuid}
      config:
        enabled: true
        format: YAML
        profile-separator: '-'
        data-key: data
        watch:
          enabled: true
          delay: 1000