spring:
  sql:
    init:
      mode: never
      encoding: utf-8
  datasource:
    hikari:
      maximum-pool-size: 30
      connection-timeout: 10000
      validation-timeout: 3000
      max-lifetime: 1800000
      idle-timeout:   600000
      keepalive-time: 120000
      leak-detection-threshold: 30000
      auto-commit: true
      pool-name: HikariPool-${spring.application.name}
      initialization-fail-timeout: 30000
      minimum-idle: 7
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        type:
          preferred_java_type_jdbc_code_for_enum: 24
        default_batch_fetch_size: 128
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 128
          fetch_size: 128
          time_zone: Asia/Shanghai
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: false
    defer-datasource-initialization: true
